package Pojos_BBDD2;
// Generated 27-feb-2018 13:22:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;



/**
 * ComunidadAutonoma generated by hbm2java
 */

public class ComunidadAutonoma  implements java.io.Serializable {


   
     private int codCom;
     
     private String nombreCom;
     private Set provinces = new HashSet(0);

    public ComunidadAutonoma() {
    }

	
    public ComunidadAutonoma(int codCom) {
        this.codCom = codCom;
    }
    public ComunidadAutonoma(int codCom, String nombreCom, Set provinces) {
       this.codCom = codCom;
       this.nombreCom = nombreCom;
       this.provinces = provinces;
    }
   
    public int getCodCom() {
        return this.codCom;
    }
    
    public void setCodCom(int codCom) {
        this.codCom = codCom;
    }
    public String getNombreCom() {
        return this.nombreCom;
    }
    
    public void setNombreCom(String nombreCom) {
        this.nombreCom = nombreCom;
    }
    public Set getProvinces() {
        return this.provinces;
    }
    
    public void setProvinces(Set provinces) {
        this.provinces = provinces;
    }
    
    //toString
    public String toString(){
        return "Nombre: "+this.getNombreCom();
    }




}


