package Pojos_BBDD1;
// Generated 26-feb-2018 13:27:06 by Hibernate Tools 4.3.1



/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private int codCiudad;
     private Provincia provincia;
     private String nombre;

    public Ciudad() {
    }

	
    public Ciudad(int codCiudad, Provincia provincia) {
        this.codCiudad = codCiudad;
        this.provincia = provincia;
    }
    public Ciudad(int codCiudad, Provincia provincia, String nombre) {
       this.codCiudad = codCiudad;
       this.provincia = provincia;
       this.nombre = nombre;
    }
   
    public int getCodCiudad() {
        return this.codCiudad;
    }
    
    public void setCodCiudad(int codCiudad) {
        this.codCiudad = codCiudad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    //To String
    @Override
    public String toString(){
        return "Nombre ciudad: "+this.getNombre()+" Codigo ciudad: "+this.getCodCiudad()+"\n"
                + "Nombre provincia: "+this.getProvincia().getNombre();
    }




}


