package Pojos_BBDD1;
// Generated 26-feb-2018 13:27:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private int codPais;
     private String nombrePais;
     private Set provincias = new HashSet(0);

    public Pais() {
    }
    
    //Nuevo constructor
    public Pais(int codPais, String nombre){
       this.codPais = codPais;
       this.nombrePais= nombre;
    }
	
    public Pais(int codPais) {
        this.codPais = codPais;
    }
    public Pais(int codPais, String nombrePais, Set provincias) {
       this.codPais = codPais;
       this.nombrePais = nombrePais;
       this.provincias = provincias;
    }
   
    public int getCodPais() {
        return this.codPais;
    }
    
    public void setCodPais(int codPais) {
        this.codPais = codPais;
    }
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Set getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set provincias) {
        this.provincias = provincias;
    }

    @Override
    public String toString() {
        return "Pais{" + "codPais=" + codPais + ", nombrePais=" + nombrePais + ", provincias=" + provincias + '}';
    }
}


