package Pojos_BBDD1;
// Generated 26-feb-2018 13:27:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private int codProv;
     private Pais pais;
     private String nombre;
     private Set ciudads = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(int codProv) {
        this.codProv = codProv;
    }
    public Provincia(int codProv, Pais pais, String nombre, Set ciudads) {
       this.codProv = codProv;
       this.pais = pais;
       this.nombre = nombre;
       this.ciudads = ciudads;
    }
   
    public int getCodProv() {
        return this.codProv;
    }
    
    public void setCodProv(int codProv) {
        this.codProv = codProv;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }

    //To String
    public String toString(){
        return "Nombre Provincia: "+this.getNombre()+", Codigo: "+this.getCodProv()+"\n"
        + "Pais: "+this.getPais().getNombrePais()+" cuyo codigo es: "+this.getPais().getCodPais()+"\n"
                + "Las ciudades que lo componen son: "+this.getCiudads().toString();
    }



}


